quarkus:
  http:
    port: 8081
    host: 0.0.0.0
    cors:
      enabled: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "accept,authorization,content-type,x-requested-with"
      access-control-max-age: 24H

  datasource:
    db-kind: mysql
    username: root
    password:
    jdbc:
      url: jdbc:mysql://localhost:3306/e-parapheur

  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

  liquibase:
    migrate-at-start: true
    change-log: db/changelog.xml

  log:
    level: INFO
    category:
      com.eparapheur:
        level: DEBUG

  smallrye-openapi:
    info:
      title: e-Parapheur API
      version: "1.0.0"
    path: /openapi

  # Mailer Configuration
  mailer:
    from: "e-Parapheur Test <noreply@cryptoneomail.com>"
    host: ssl0.ovh.net
    username: noreply@cryptoneomail.com
    password: "m@!l*20&24#"
    mock: false
    port: 465
    ssl: true
    start-tls: DISABLED
    auth: true
    trust-all: true

  # Configuration pour le stockage des fichiers
  file:
    storage:
      path: ${FILE_STORAGE_PATH:./uploads/documents}
      max-file-size: 10485760  # 10 MB en bytes

mp:
  jwt:
    verify:
      publickey:
        location: resources/publicKey.pem

smallrye:
  jwt:
    sign:
      key:
        location: resources/privateKey.pem